# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20160214_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresses',
            options={'ordering': ('address_id',), 'verbose_name': 'Store Address', 'verbose_name_plural': 'Store Addresses'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ('item_name',), 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='lists',
            options={'ordering': ('list_name',), 'verbose_name': 'List', 'verbose_name_plural': 'Lists'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('product_name',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='stores',
            options={'ordering': ('store_name',), 'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ('tag_name',), 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='lists',
            name='is_premade',
            field=models.BooleanField(default=0),
        ),
    ]
