# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 19:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0002_auto_20160306_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='list_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
