# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0004_auto_20160306_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='list_tags',
            field=models.ManyToManyField(related_name='tags', to='data_manager.tags'),
        ),
    ]
