# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 19:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0005_auto_20160306_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='containing_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_manager.lists'),
        ),
        migrations.AlterField(
            model_name='items',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_manager.products'),
        ),
        migrations.AlterField(
            model_name='lists',
            name='list_tags',
            field=models.ManyToManyField(to='data_manager.tags'),
        ),
        migrations.AlterField(
            model_name='lists',
            name='list_users',
            field=models.ManyToManyField(related_name='lists_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='products',
            name='store',
            field=models.ManyToManyField(to='data_manager.stores'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='store_address',
            field=models.ManyToManyField(to='data_manager.addresses'),
        ),
    ]
