# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 19:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0006_auto_20160306_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
