# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0007_auto_20160306_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='store',
            field=models.ManyToManyField(related_name='stores_products', to='data_manager.stores'),
        ),
    ]
