# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0008_auto_20160306_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='list_tags',
            field=models.ManyToManyField(related_name='lists_tags', to='data_manager.tags'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='store_address',
            field=models.ManyToManyField(related_name='stores_addresses', to='data_manager.addresses'),
        ),
    ]
