# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0009_auto_20160306_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='containing_list',
        ),
        migrations.RemoveField(
            model_name='items',
            name='item_creator',
        ),
        migrations.RemoveField(
            model_name='items',
            name='product',
        ),
        migrations.RemoveField(
            model_name='lists',
            name='list_creator',
        ),
        migrations.RemoveField(
            model_name='lists',
            name='list_tags',
        ),
        migrations.RemoveField(
            model_name='lists',
            name='list_users',
        ),
        migrations.RemoveField(
            model_name='products',
            name='store',
        ),
        migrations.RemoveField(
            model_name='stores',
            name='store_address',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='tag_creator',
        ),
        migrations.DeleteModel(
            name='addresses',
        ),
        migrations.DeleteModel(
            name='items',
        ),
        migrations.DeleteModel(
            name='lists',
        ),
        migrations.DeleteModel(
            name='products',
        ),
        migrations.DeleteModel(
            name='stores',
        ),
        migrations.DeleteModel(
            name='tags',
        ),
    ]
