# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 21:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0011_auto_20160306_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='list_users',
            field=models.ManyToManyField(related_name='users_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
