# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0013_auto_20160412_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_details',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_quantity',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
